name: 'Deploy to GitHub Pages'
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Setup Node'
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn
      - name: 'Use SSH agent'
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: 'Deploy to GitHub Pages'
        env:
          USE_SSH: true      
        run: |
          export NODE_OPTIONS="--max_old_space_size=4096"
          git config --global user.email "action@github.com"
          git config --global user.name "actions-user"
          yarn
          yarn deploy
